// <auto-generated />
namespace AppLunch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class NewLocationColumnsVarcharColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewLocationColumnsVarcharColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201707130001547_NewLocationColumnsVarcharColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
